name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version
          required: true
        - label: I have read the documentation
          required: true
          
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      options:
        - v1.1.0 (latest)
        - v1.0.0
        - Development/main branch
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS 10.15+
        - Ubuntu 20.04+
        - Ubuntu 22.04+
        - Other Linux distribution
        - Other (please specify in description)
    validations:
      required: true
      
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - Python 3.8
        - Python 3.9
        - Python 3.10
        - Python 3.11
        - Python 3.12
        - Other (please specify in description)
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - GUI Application
        - Command Line Interface
        - Core Converter
        - Installation/Setup
        - Documentation
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Tell us what you expected!
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open GUI application
        2. Click on '...'
        3. Select file '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: error-message
    attributes:
      label: Error message
      description: If applicable, paste the complete error message
      render: shell
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (file sizes, special characters, etc.)
      
  - type: checkboxes
    id: file-sharing
    attributes:
      label: File sharing (optional)
      description: Can you share a sample file that reproduces the issue?
      options:
        - label: I can provide a sample OFT file that demonstrates the issue
        - label: The file contains sensitive information and cannot be shared
        - label: I will try to create a minimal test case